// <auto-generated />
namespace PRTracker.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Milestone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Milestone));
        
        string IMigrationMetadata.Id
        {
            get { return "201506182204394_Milestone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
