// <auto-generated />
namespace PRTracker.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class PullRequestDates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PullRequestDates));
        
        string IMigrationMetadata.Id
        {
            get { return "201501140310326_PullRequestDates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
